version: '3.9'

services:
  fastapi-server:
    build: ./app
    container_name: trigger_api
    ports:
      - "5000:8000"
    volumes:
      - ./app/scripts:/app/scripts
      - ./app/infra:/app/infra
    environment:
      - PYTHONUNBUFFERED=1
